apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.registries.mittwald.de
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: phase
    name: Status
    type: string
  group: registries.mittwald.de
  names:
    kind: Registry
    listKind: RegistryList
    plural: registries
    singular: registry
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Registry is the Schema for the registries API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RegistrySpec defines the desired state of a Registry
          properties:
            credential:
              description: Credential keeps the access key and/or secret for the related
                registry
              properties:
                access_key:
                  description: The key of the access account, for OAuth token, it
                    can be empty
                  type: string
                access_secret:
                  description: The secret or password for the key
                  type: string
                type:
                  description: Type of the credential
                  type: string
              required:
              - access_key
              - access_secret
              - type
              type: object
            description:
              type: string
            id:
              description: Registry ID, gets autogenerated (last project id +1) when
                left empty
              format: int64
              type: integer
            insecure:
              description: Whether or not the TLS certificate will be verified when
                Harbor tries to access the registry
              type: boolean
            name:
              type: string
            parentInstance:
              description: ParentInstance is a LocalObjectReference to the name of
                the harbor instance the registry is created for
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            token_service_url:
              description: TokenServiceURL is only used for local harbor instances
                to avoid the requests passing through the external proxy for now
              type: string
            type:
              description: 'TODO: A string enum would be appropriate here, though
                kubebuilder seems to not like this annotation: "+kubebuilder:validation:Enum:=harbor,docker-hub,docker-registry,huawei-SWR,google-gcr,aws-ecr,azure-acr,ali-acr,jfrog-artifactory,quay-io,gitlab,helm-hub"
                Leaving it as is for the time being'
              type: string
            url:
              description: Target URL of the registry
              type: string
          required:
          - name
          - parentInstance
          - type
          - url
          type: object
        status:
          description: RegistryStatus defines the observed state of Registry
          properties:
            lastTransition:
              description: Time of last observed transition into this state
              format: date-time
              type: string
            message:
              type: string
            name:
              type: string
            phase:
              type: string
          required:
          - message
          - name
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
