apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "chart.fullname" . }}-smtp
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          "kube-mail.helmich.me/smtp-access": "true"
    ports:
    - protocol: TCP
      port: {{ .Values.smtp.service.internalPort }}
