image:
  repository: quay.io/mittwald/kubernetes-replicator
  #tag: stable # if no tag is given, the chart's appVersion is used
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

args: []
  # - -resync-period=30m
  # - -allow-all=false

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podLabels: {}

podAnnotations: {}
