{{- if .Values.installHarborChartRepo }}
apiVersion: registries.mittwald.de/v1alpha2
kind: InstanceChartRepository
metadata:
  name: harbor
  labels:
  {{- include "harbor-operator.labels" . | nindent 4 }}
spec:
  name: harbor
  url: https://helm.goharbor.io
{{- end }}