{{- range $instance := .Values.instances }}
  {{- range $registry := .registries }}
apiVersion: registries.mittwald.de/v1alpha2
kind: Registry
metadata:
  name: {{ $instance.name }}-{{ $registry.name }}
  labels:
  {{- include "harbor-operator.labels" $ | nindent 4 }}
spec:
  parentInstance:
    name: {{ $instance.name }}
  name: {{ $registry.name }}
  type: {{ $registry.type }}
  url: {{ $registry.url }}


  {{- if $registry.description }}
  description: {{ $registry.description }}
  {{- end }}

  {{- with $registry.credential }}
  credential:
  {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if $registry.insecure }}
  insecure: {{ $registry.insecure }}
  {{- end }}
---
  {{- end }}
{{- end }}