{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-htpasswd
  labels: {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  .htpasswd: |-
  {{- range $user, $password := .Values.auth.htpasswd }}
    {{ $user }}:{{ $password }}
  {{- end }}
{{- end }}